function Ls1 = MGspringlength(in1,in2,L0,K,in5,in6)
%MGSPRINGLENGTH
%    LS1 = MGSPRINGLENGTH(IN1,IN2,L0,K,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Dec-2017 16:52:48

com11 = in5(1,:);
com12 = in5(2,:);
ps11 = in1(1,:);
ps12 = in1(2,:);
ps21 = in2(1,:);
ps22 = in2(2,:);
theta1 = in6(3,:);
x1 = in6(1,:);
y1 = in6(2,:);
t2 = cos(theta1);
t3 = com12-ps22;
t4 = sin(theta1);
t5 = com11-ps21;
Ls1 = [ps11-x1+t2.*t5-t3.*t4;ps12-y1+t2.*t3+t4.*t5];
