function Ls2 = MMspringlength(in1,in2,L0,K,in5,in6,in7)
%MMSPRINGLENGTH
%    LS2 = MMSPRINGLENGTH(IN1,IN2,L0,K,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Dec-2017 16:52:48

com11 = in5(1,:);
com12 = in5(2,:);
com21 = in6(1,:);
com22 = in6(2,:);
ps11 = in1(1,:);
ps12 = in1(2,:);
ps21 = in2(1,:);
ps22 = in2(2,:);
theta1 = in7(3,:);
theta2 = in7(6,:);
x1 = in7(1,:);
x2 = in7(4,:);
y1 = in7(2,:);
y2 = in7(5,:);
t2 = cos(theta1);
t3 = com12-ps12;
t4 = cos(theta2);
t5 = com22-ps22;
t6 = sin(theta1);
t7 = com11-ps11;
t8 = sin(theta2);
t9 = com21-ps21;
Ls2 = [x1-x2-t2.*t7+t3.*t6+t4.*t9-t5.*t8;y1-y2-t2.*t3+t4.*t5-t6.*t7+t8.*t9];
