function Es2 = MMspringenergy(in1,in2,L0,K,in5,in6,in7)
%MMSPRINGENERGY
%    ES2 = MMSPRINGENERGY(IN1,IN2,L0,K,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    25-Dec-2017 16:52:50

com11 = in5(1,:);
com12 = in5(2,:);
com21 = in6(1,:);
com22 = in6(2,:);
ps11 = in1(1,:);
ps12 = in1(2,:);
ps21 = in2(1,:);
ps22 = in2(2,:);
theta1 = in7(3,:);
theta2 = in7(6,:);
x1 = in7(1,:);
x2 = in7(4,:);
y1 = in7(2,:);
y2 = in7(5,:);
t3 = cos(theta1);
t4 = com12-ps12;
t5 = cos(theta2);
t6 = com22-ps22;
t7 = sin(theta1);
t8 = com11-ps11;
t9 = sin(theta2);
t10 = com21-ps21;
t2 = x1-x2-t3.*t8+t4.*t7+t5.*t10-t6.*t9;
t11 = y1-y2-t3.*t4+t5.*t6-t7.*t8+t9.*t10;
t12 = L0-sqrt(t2.^2+t11.^2);
Es2 = K.*t12.^2.*(1.0./2.0);
